language: node_js
node_js:
  - "8.5.0"
if: tag IS blank

cache:
  directories:
    - node_modules
    - $HOME/.npm

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1

install:
  - pwd
  - npm install

before_script: greenkeeper-lockfile-update

script:
  - pwd
  - npm run build:lib
  - npm test -- --single-run

after_script: greenkeeper-lockfile-upload

before_deploy:
  - pwd
  - cd material2-extensions

deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $AUTH_TOKEN
  skip_cleanup: true

after_deploy:
  - export GIT_TAG=v$(npm run version --silent)
  - git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GITHUB_KEY@github.com/sandervalstar/material2-extensions $GIT_TAG > /dev/null 2>&1
